### ISSUE TITLE
bug: スレッド管理者でないユーザでも他のスレッドの管理者画面に遷移できてしまう

### ISSUE THREAD

**Issue by Ojoxux** [Team-ONY/TeamONY-Ogiri-Hub#26]
## バグ発生までの操作手順

1. URLの`thread/thread.id`の`thread`を`admin`に変更
2. 該当する`thread.id`の管理者画面に非管理者ユーザでもアクセスできる

## バグが発生した環境

- おそらく全てのOSで発生

## 期待される動作

- [ ] 非管理者が`admin`にアクセスしようとしたときにエラーが出て弾かれるようになる

**Comment by kamura0x0** [comment]
テキストの色の問題で表示されてないようになっている
