### ISSUE TITLE
bug: スレッドを開いて上にスクロールすると下に戻される

### ISSUE THREAD

**Issue by UMAItaiyaki** [Team-ONY/TeamONY-Ogiri-Hub#78]
## 発生したバグの説明 
スレッド開いてある程度コメントした後、上のほうにスクロールすると一番下の方に戻される
## バグ発生までの操作手順

1. スレッドを開く
2. ある程度コメントする
3. 上の方にスクロールする
4. 一番下に戻される

## バグが発生した環境

- ほぼ全てのOSで発生

**Comment by Ojoxux** [comment]
PR #81 で解決
